_global:
  title_suffix: 'Your Site'
  footer_text: 'Hey'

index:
  _global:
    title: 'Home'
  _pieces:
    - layouts/layout:
        _pieces:
          - header: {}
          - posts:
              _pieces:
                - posts/post:
                    title: 'A block title'
                    content: '<p>Some paragraph</p>'
                - posts/post:
                    title: 'Another'
                    content: '<p>Another thing.</p>'
                - posts/post:
                    title: 'And another'
                    content: '<p>Blah blah blah.</p>'
          - footer: {}

about:
  _global:
    title: 'About'
  _pieces:
    - layouts/layout:
        _pieces:
          - header: {}
          - posts/post:
              title: 'About Author'
              content: '<p>He is a cool dude.</p>'
          - footer: {}
