_global:
  title_suffix: 'Your Site'
  footer_text: 'Hey'

index:
  _global:
    title: 'Home'
  _pieces:
    - layout:
        _pieces:
          - post:
              title: 'A block title'
              content: '<p>Some paragraph</p>'
          - post:
              title: 'Another'
              content: '<p>Another thing.</p>'
          - post:
              title: 'And another'
              content: '<p>Blah blah blah.</p>'

about:
  _global:
    title: 'About'
  _pieces:
    - layout:
        _pieces:
          - post:
              title: 'About Author'
              content: '<p>He is a cool dude.</p>'
