_global:
  title_suffix: 'Your Site'

_layout: 'layout'

index:
  _global:
    title: 'Home'
  pieces:
    - post:
        title: 'A block title'
        content: '<p>Some paragraph</p>'
    - post:
        title: 'Another'
        content: '<p>Another thing.</p>'
    - post:
        title: 'And another'
        content: '<p>Blah blah blah.</p>'

about:
  _global:
    title: 'About'
  pieces:
    - post:
        title: 'About Author'
        content: '<p>He is a cool dude.</p>'
