_global:
  title: 'Styleguide!'

index:
  _pieces:
    - layouts/pieces:
        _pieces:
          - header:
              _global:
                critical: yes
              _pieces:
                - branding: {}
          - articles/articles_introduction:
              intro: '<p>Some articles'
              critical: yes
          - articles/article: { title: 'Nice', content: '<p>Bob' }
          - articles/article: { title: 'Bob', content: '<p>Some nice example content' }
          - articles/article: { title: 'Cooob', content: '<p>Some nice example content' }
          - articles/article: { title: 'Adele', content: '<p>Some nice example content' }
          - articles/article: { title: 'Hehe', content: '<p>Some nice example content' }
          - footer: {}

info:
  _pieces:
    - layouts/pieces:
        title: 'About this style guide'
        _pieces:
          - articles/article: { title: 'About this guide' }
